include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    # 代码风格
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # 命名规范
    constant_identifier_names: true
    file_names: true
    package_names: true
    
    # 代码质量
    avoid_print: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_void: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    throw_in_finally: true
    unnecessary_statements: true
    
    # Flutter 特定
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
